### ISSUE TITLE
[Project submission] Reducing Docker Image Size for Submission

### ISSUE THREAD

**Issue by vanouri** [PiLab-CAU/AISystem-2402#18]
Hello,
I'm trying to submit the Docker image file for the project, but I'm facing issues reducing its size. Since GitHub only allows files smaller than 100 MB, I’ve tried using a smaller version of Torch and removed unnecessary files, but I still can’t make the image small enough.
Could you share how you managed to reduce the size of your Docker image to meet the requirements? Any tips or best practices would be greatly appreciated.
Thank you!

**Comment by llleeeso** [comment]
Hello, @vavarier.

One way to reduce the size of your Docker image is to modify your Dockerfile to copy only the essential files.

If the size is still too large, you can skip installing the requirements in the Dockerfile and only include the necessary files. I will install the requirements myself when evaluating the model.

While practicing, please make sure all the necessary packages are listed in the requirements.txt file and the code runs properly.

For example, in your Dockerfile, you can skip steps like `RUN pip install --upgrade pip` or `RUN pip install -r requirements.txt` as I will use the requirements.txt file already included in the Docker image to install the required packages during evaluation.

Thank you.

**Comment by vanouri** [comment]
Hello, @llleeeso,

Thank you for your response, Considering that the python:3.10-slim image alone takes up 126.97MB, would it be possible to submit a compressed .tar.gz file instead ?

**Comment by llleeeso** [comment]
Yes, submitting a compressed .tar.gz file of the Docker image would be perfectly fine.
Please ensure it contains the complete image and all necessary files.

Thank you.

**Comment by llleeeso** [comment]
Closing the issue as it appears to be resolved. 
Please feel free to reopen it or create a new issue if needed.
