### ISSUE TITLE
[Project submission] 과제 제출 시, 실행 및 압축 파일에 관한 질문

### ISSUE THREAD

**Issue by Burugi** [PiLab-CAU/AISystem-2402#19]
테스트 용으로 과제를 제출해보고자 하는데, 여러모로 막힌 부분이 있습니다.

질문은 총 2가지 입니다.
1. Run Docker Container시에 dockerignore로 인해 image 파일 안에 dataset이 없는데 어떻게 run을 해야하는지 궁금합니다. 
run 예시를 실행하면 test, train의 데이터가 없다고 실행되지 않습니다.
2. 이미지를 빌드할 때, 기존의 코드를 많이 이용해서 여러가지 파일이 들어가 있습니다.  
따라서 image 파일의 용량이 커지는 문제가 발생하는데 이를 어떻게 해결하는지 궁금합니다. 제가 짠 코드는 main.py, model.pth파일 만으로는 실행이 불가능합니다. 
+ 모든 내용을 하나의 파일(main.py)에 넣어서 실행해야하는 지 궁금합니다.
3. 아래의 질문과 유사한데 깃으로 전달하는 파일의 용량은 한정되어 있는데, 이를 어떤 식으로 전달하는 지 궁금합니다.

**Comment by llleeeso** [comment]
안녕하세요, @Burugi 님.

1. 연습 시에는 .dockerignore 파일을 수정하여 데이터셋을 포함시키거나, Docker 실행 시 로컬에 있는 데이터셋을 컨테이너에 마운트하는 방법을 사용할 수 있습니다.

2. 제출 시에는 Dockerfile을 수정하여 필요한 파일만 포함해 주세요. 예를 들어, `RUN pip install --upgrade pip`이나 `RUN pip install -r requirements.txt` 같은 단계는 생략하셔도 괜찮습니다. 대신, 필요한 패키지들이 모두 requirements.txt에 포함되어야 합니다.
또한, 모든 내용을 하나의 파일(main.py)로 통합할 필요는 없습니다.

3. 불필요한 파일을 모두 제거해도 Docker 이미지의 용량이 크다면, Pull Request를 제출해주시고, Docker 이미지는 이메일로 보내주시면 감사하겠습니다.

감사합니다.

---
1. When practicing, you can either modify the .dockerignore file to include the dataset or mount the dataset from your local machine to the container during Docker execution.

2. When submitting, please update the Dockerfile to include only the necessary files. For example, you can skip steps like `RUN pip install --upgrade pip` or `RUN pip install -r requirements.txt`. Instead, ensure that all required packages are listed in the requirements.txt file.
Additionally, it is not necessary to combine everything into a single main.py file.

3. If the Docker image size remains large even after removing unnecessary files, please submit a Pull Request and send the Docker image via email.

Thank you.

**Comment by Burugi** [comment]
답변 감사합니다!

**Comment by llleeeso** [comment]
Closing the issue as it appears to be resolved.
Please feel free to reopen it or create a new issue if needed.
